version: '3.7'

services:
  main:
    build:
      context: .
    user: node
    ports:
      - 3001:3000
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      NODE_ENV: local
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: postgres

    command: npm run start:dev

  db:
    image: postgres:14.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
